import {
  IPropertyRequestSchema,
  IPropertyResponseSchema,
} from "@/packages/server/modules/data/schemas/property.schema";

const mockProperty: IPropertyResponseSchema["data"] = {
  udprn: 11414310,
  address_line_1: "8 Marlborough Court",
  address_line_2: "Queens Road",
  address_line_3: null,
  post_town: "Buckhurst Hill",
  formatted_address:
    "8 Marlborough Court, Queens Road, Buckhurst Hill, Essex, IG9 5BN",
  postcode: "IG9 5BN",
  outcode: "IG9",
  longitude: 0.0402,
  latitude: 51.6255,
  region: "East of England",
  district: "Epping Forest",
  county: "Essex",
  last_sold: null,
  sold_history: null,
  sold_nearby: [
    {
      last_sold_date: "2023-05-23",
      address: "124, Queens Road, Buckhurst Hill, Essex, IG9 5BJ",
      short_address: "124, Queens Road",
      last_sold_amount: 1150000,
      type: "terraced",
      estimate: 1173000,
      total_floor_area: "150",
    },
    {
      last_sold_date: "2023-05-23",
      address: "4, Andrews Close, Buckhurst Hill, Essex, IG9 5BL",
      short_address: "4, Andrews Close",
      last_sold_amount: 575000,
      type: "terraced",
      estimate: 586000,
      total_floor_area: "101",
    },
    {
      last_sold_date: "2022-08-30",
      address: "85, Princes Road, Buckhurst Hill, Essex, IG9 5DZ",
      short_address: "85, Princes Road",
      last_sold_amount: 920000,
      type: "terraced",
      estimate: 898000,
      total_floor_area: "112",
    },
    {
      last_sold_date: "2022-07-29",
      address: "97, Princes Road, Buckhurst Hill, Essex, IG9 5DZ",
      short_address: "97, Princes Road",
      last_sold_amount: 665000,
      type: "terraced",
      estimate: 661000,
      total_floor_area: "74",
    },
    {
      last_sold_date: "2022-06-28",
      address: "129, Queens Road, Buckhurst Hill, Essex, IG9 5BH",
      short_address: "129, Queens Road",
      last_sold_amount: 750000,
      type: "terraced",
      estimate: 750000,
      total_floor_area: "102",
    },
    {
      last_sold_date: "2022-06-01",
      address: "100, Queens Road, Buckhurst Hill, Essex, IG9 5BS",
      short_address: "100, Queens Road",
      last_sold_amount: 1360000,
      type: "detached",
      estimate: 1359000,
      total_floor_area: "162",
    },
    {
      last_sold_date: "2022-02-18",
      address: "30, Westbury Lane, Buckhurst Hill, Essex, IG9 5PL",
      short_address: "30, Westbury Lane",
      last_sold_amount: 1025000,
      type: "terraced",
      estimate: 1051000,
      total_floor_area: "140",
    },
    {
      last_sold_date: "2022-02-18",
      address: "56, Princes Road, Buckhurst Hill, Essex, IG9 5DZ",
      short_address: "56, Princes Road",
      last_sold_amount: 560000,
      type: "semi-detached",
      estimate: 574000,
      total_floor_area: "117.04",
    },
    {
      last_sold_date: "2022-01-10",
      address: "113, Princes Road, Buckhurst Hill, Essex, IG9 5DX",
      short_address: "113, Princes Road",
      last_sold_amount: 650000,
      type: "terraced",
      estimate: 666000,
      total_floor_area: "111",
    },
  ],
  valuation_estimate: 437000,
  valuation_upper: 496000,
  valuation_lower: 379000,
  lettings_estimate: 1730,
  lettings_upper: 1970,
  lettings_lower: 1500,
  valuation_indexed: null,
  valuation_indexed_upper: null,
  valuation_indexed_lower: null,
  property_type: null,
  built_form: "mid-terrace",
  current_energy_rating: "C",
  potential_energy_rating: "C",
  current_energy_efficiency: 74,
  potential_energy_efficiency: 79,
  lighting_cost_current: 84,
  heating_cost_current: 367,
  hot_water_cost_current: 89,
  hotwater_description: "From main system",
  total_floor_area: 72,
  mains_gas_flag: "Y",
  extension_count: 0,
  number_habitable_rooms: 3,
  number_open_fireplaces: 0,
  windows_description: "Fully double glazed",
  mainheat_description: "Boiler and radiators, mains gas",
  main_fuel: "mains gas (not community)",
  tenure: "rental (private)",
  construction_age_band: "England and Wales: 1950-1966",
  beds: null,
  beds_estimate: 2,
  listing_price_history: [null],
  listing_date: null,
};

export { mockProperty };
